POST http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hZGVlbUBleGFtcGxlLmNvbSIsImV4cCI6MTc2NTYzODg1MCwidXNlcklkIjoxfQ.qe65cEE2P_Z6OgmJb-A3MbKH8ia1Nr0Go5v0DKCWy3Y

{
    "name": "test event ",
    "description": " test event!!",
    "location": "A test location",
    "dateTime": "2025-12-06T15:30:00.000Z"
}

